### ISSUE TITLE
请问用postman测试授权码模式，要怎么操作？

### ISSUE THREAD

**Issue by zsoftbuilder** [EalenXie/spring-oauth2-authenticator#1]
我在postman里直接post方式http://localhost:8080/login?username=ealenxie&password=admin报下面的错误。请问不用浏览器，直接用postman要怎么测试整个授权码模式的登录（就用postman测试授权码最后能获取到最后的token）
{
    "status": 401,
    "message": "unauthorized client",
    "data": null
}

**Comment by EalenXie** [comment]
Basic 认证头加了么。

**Comment by zsoftbuilder** [comment]
请问这个认证头是否可以去除？我用密码模式好像不需要再多一个认证吧

**Comment by EalenXie** [comment]
不可去除，SpringOauth2中认证头代表的客户端身份验证信息，可见 [https://www.oauth.com/oauth2-servers/access-tokens/password-grant/](https://www.oauth.com/oauth2-servers/access-tokens/password-grant/) 。
是否需要再多认证，建议你先看看Oauth2.0的几个基本角色的关系。
