### ISSUE TITLE
启动后报错401

### ISSUE THREAD

**Issue by junecarla** [EalenXie/spring-oauth2-authenticator#3]
步骤：
1.创建数据库表
2.修改数据库连接
3.启动
4.使用postman调用返回401
localhost:8080/oauth/token?grant_type=client_credentials
![image](https://user-images.githubusercontent.com/87795879/203688975-8c59c2eb-c8cf-4b5e-8bfb-ab733c48db5b.png)

**Comment by Aichen517** [comment]
我也遇到了同样的问题 应该是密码有问题 这个是加密过密码 应该是要提供 原明文密码

**Comment by Aichen517** [comment]
事实也确实如此 测试出来的 client 明文密码是 123456

**Comment by Aichen517** [comment]
事实也确实如此 测试出来的 client 明文密码是 123456
![image](https://user-images.githubusercontent.com/76988466/207811957-aaab31d3-e352-41f3-9efa-32a0a2165b23.png)

**Comment by EalenXie** [comment]
> 步骤： 1.创建数据库表 2.修改数据库连接 3.启动 4.使用postman调用返回401 localhost:8080/oauth/token?grant_type=client_credentials ![image](https://user-images.githubusercontent.com/87795879/203688975-8c59c2eb-c8cf-4b5e-8bfb-ab733c48db5b.png)

Basic Auth里面的认证密码传123456就行
